/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Tool {
  'verified' : boolean,
  'deal' : string,
  'name' : string,
  'tags' : Array<string>,
  'description' : string,
  'website' : string,
  'category' : string,
  'rating' : number,
}
export interface _SERVICE {
  'addTool' : ActorMethod<
    [string, string, string, number, boolean, Array<string>, string, string],
    undefined
  >,
  'filterByCategory' : ActorMethod<[string], Array<Tool>>,
  'getAllTools' : ActorMethod<[], Array<Tool>>,
  'getCategories' : ActorMethod<[], Array<string>>,
  'getToolByName' : ActorMethod<[string], Tool>,
  'searchTools' : ActorMethod<[string], Array<Tool>>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];